package com.miguel.tibiamerchants.domain.models

import com.miguel.tibiamerchants.data.network.retrofit.responses.TibiaTradeItemProfileModel

data class TibiaTradeItemProfileModelDto(
    val id: Int? = null,
    val itemName: String? = null,
    val imageUrl: String? = null,
    val itemAmount: Int? = null,
    val itemId: Int? = null,
    val tibiaId: Int? = null,
    val houseId: Int? = null,
    val houseName: String? = null,
    val itemTier: Int? = null,
    val itemLook: String? = null,
    val username: String? = null,
    val userId: Int? = null,
    val price: Long? = null,
    val currencyType: Int? = null,
    val roomsImages: List<String>? = null,
    val type: Int? = null,
    val worldId: Int? = null,
    val worldName: String? = null,
    val worldPvpType: String? = null,
    val worldBattleEyeColor: String? = null,
    val createdAt: String? = null,
    val viewCount: Int? = null,
    val autoRenew: Boolean = false,
    val autoHighlight: Boolean = false,
    val town: String? = null,
    val size: Int? = null,
    val rooms: Int? = null,
    val beds: Int? = null,
    val floors: Int? = null,
    val rent: Int? = null,
    val windows: Int? = null,
    val furnitures: String? = null,
    val coordinates: String? = null,
    val convertedPrice: Long? = null,
    val avatar: String? = null,
    val tibiaBlackjackUsername: String? = null,
    val rookgaard: Boolean = false,
    val guildhall: Boolean = false,
    val userVerified: Boolean = false,
    val highlightPrepaid: Boolean = false,
    // Market price
    val referencePrice: Int? = null,
    val sampleSize: Int? = null,
    val source: String? = null,
    // Item profile flags
    val hasFeedImage: Boolean = false,
    val hasStoryImage: Boolean = false,
    val hasFeedPtBrImage: Boolean = false,
    val hasStoryPtBrImage: Boolean = false,
    val screenshotCount: Int? = null,
    val closed: Boolean = false,
    val active: Boolean = false
)

fun TibiaTradeItemProfileModel.toDomain(): TibiaTradeItemProfileModelDto {
    return TibiaTradeItemProfileModelDto(
        id = info.id,
        itemName = info.itemName,
        imageUrl = info.imageUrl,
        itemAmount = info.itemAmount,
        itemId = info.itemId,
        tibiaId = info.tibiaId,
        houseId = info.houseId,
        houseName = info.houseName,
        itemTier = info.itemTier,
        itemLook = info.itemLook,
        username = info.username,
        userId = info.userId,
        price = info.price,
        currencyType = info.currencyType,
        roomsImages = info.roomsImages,
        type = info.type,
        worldId = info.worldId,
        worldName = info.worldName,
        worldPvpType = info.worldPvpType,
        worldBattleEyeColor = info.worldBattleEyeColor,
        createdAt = info.createdAt,
        viewCount = info.viewCount,
        autoRenew = info.autoRenew,
        autoHighlight = info.autoHighlight,
        town = info.town,
        size = info.size,
        rooms = info.rooms,
        beds = info.beds,
        floors = info.floors,
        rent = info.rent,
        windows = info.windows,
        furnitures = info.furnitures,
        coordinates = info.coordinates,
        convertedPrice = info.convertedPrice,
        avatar = info.avatar,
        tibiaBlackjackUsername = info.tibiaBlackjackUsername,
        rookgaard = info.rookgaard,
        guildhall = info.guildhall,
        userVerified = info.userVerified,
        highlightPrepaid = info.highlightPrepaid,
        referencePrice = marketPrice?.referencePrice,
        sampleSize = marketPrice?.sampleSize,
        source = marketPrice?.source,
        hasFeedImage = hasFeedImage,
        hasStoryImage = hasStoryImage,
        hasFeedPtBrImage = hasFeedPtBrImage,
        hasStoryPtBrImage = hasStoryPtBrImage,
        screenshotCount = screenshotCount,
        closed = closed,
        active = active
    )
}
